name: Build dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm install
      - run: echo "MONGO_URI=${{ secrets.MONGO_URI_DEV }}" >> $GITHUB_ENV
      - run: npm run test
