name: Deploy Master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm install
      - run: echo "MONGO_URL=${{ secrets.MONGO_URI_PROD }}" >> $GITHUB_ENV
      - run: npm run test